######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 21 23:10:16 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += box.h mainwindow.h utils.h
FORMS += mainwindow.ui
SOURCES += box.cpp main.cpp mainwindow.cpp
