######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 21 20:33:40 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += box.h mainwindow.h utils.h
FORMS += mainwindow.ui
SOURCES += box.cpp main.cpp mainwindow.cpp
