######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 23 23:21:37 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += box.h mainwindow.h utils.h
FORMS += mainwindow.ui
SOURCES += box.cpp main.cpp mainwindow.cpp
