######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 24 07:33:40 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += box.h gamemanager.h mainwindow.h utils.h
FORMS += mainwindow.ui
SOURCES += box.cpp gamemanager.cpp main.cpp mainwindow.cpp

DISTFILES +=

RESOURCES += \
    resources.qrc
